// Marker to identify Open Review comments
const REVIEW_MARKER = '*Generated by Open Review*';
const METADATA_START = '<!-- open-review:meta';
const METADATA_END = '-->';

/**
 * Format date with timezone
 */
function formatTimestamp(date = new Date(), timezone = 'UTC') {
  try {
    return date.toLocaleString('en-US', {
      timeZone: timezone,
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    });
  } catch (error) {
    // Fallback to UTC if timezone is invalid
    console.warn(`Invalid timezone '${timezone}', falling back to UTC`);
    return date.toLocaleString('en-US', {
      timeZone: 'UTC',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    });
  }
}

/**
 * Format metadata block for comment
 */
function formatMetadata(version) {
  return `${METADATA_START}\nversion: ${version}\ngenerated: ${new Date().toISOString()}\n${METADATA_END}`;
}

function formatForGitHub(result, version = 1, timezone = 'UTC') {
  // Verdict mapping per TEMPLATE.md
  const verdicts = {
    approve: { icon: '✅', text: '**LGTM** — approve and merge' },
    request_changes: { icon: '⚠️', text: '**Changes requested** — do not merge' },
    comment: { icon: '⏸️', text: '**Hold** — let\'s discuss the approach' }
  };

  const v = verdicts[result.verdict] || verdicts.comment;
  let body = `${v.icon} ${v.text}\n\n`;

  // Summary (required when not approved)
  if (result.verdict !== 'approve' && result.summary) {
    body += `${result.summary}\n\n`;
  }

  // Group findings by type/severity
  const findings = result.findings || [];
  const critical = findings.filter(f => f.severity === 'critical');
  const warnings = findings.filter(f => f.severity === 'warning');
  const questions = findings.filter(f => f.type === 'question');
  const suggestions = findings.filter(f => f.type === 'suggestion' || (f.severity === 'info' && f.type !== 'question'));

  // Must Fix - Critical blocking issues
  if (critical.length > 0) {
    body += '🔴 Must fix\n';
    if (result.sectionSummaries?.mustFix) {
      body += `${result.sectionSummaries.mustFix}\n`;
    }
    body += '\n';
    critical.forEach((f, i) => {
      body += `${i + 1}. **${f.title}**`;
      if (f.file) {
        body += ` — \`${f.file}${f.line ? ':' + f.line : ''}\``;
      }
      body += '\n';

      // Add description if present
      if (f.description) {
        body += `   ${f.description}\n`;
      }

      // Add suggested fix if present
      if (f.suggestedFix) {
        body += '\n   **Suggested fix:**\n';
        body += '   ```suggestion\n';
        body += `   ${f.suggestedFix.split('\n').join('\n   ')}\n`;
        body += '   ```\n';
      }
      body += '\n';
    });
  }

  // Should Fix - Non-blocking improvements
  if (warnings.length > 0) {
    body += '🟡 Should fix\n';
    if (result.sectionSummaries?.shouldFix) {
      body += `${result.sectionSummaries.shouldFix}\n`;
    }
    body += '\n';
    warnings.forEach(f => {
      body += `- **${f.title}**`;
      if (f.file) {
        body += ` — \`${f.file}${f.line ? ':' + f.line : ''}\``;
      }
      body += '\n';

      // Add description if present
      if (f.description) {
        body += `  ${f.description}\n`;
      }

      // Add suggested fix if present
      if (f.suggestedFix) {
        body += '\n  **Suggested fix:**\n';
        body += '  ```suggestion\n';
        body += `  ${f.suggestedFix.split('\n').join('\n  ')}\n`;
        body += '  ```\n';
      }
      body += '\n';
    });
  }

  // Questions - Discussion prompts
  if (questions.length > 0) {
    body += '💬 Questions for the team\n';
    if (result.sectionSummaries?.questions) {
      body += `${result.sectionSummaries.questions}\n`;
    }
    body += '\n';
    questions.forEach(f => {
      body += `- **${f.title}**\n`;
      if (f.description) {
        body += `  ${f.description}\n`;
      }
      body += '\n';
    });
  }

  // Suggestions - Nice-to-have (collapsed by default)
  if (suggestions.length > 0) {
    body += '💡 Suggestions (non-blocking)\n';

    // Section summary is ALWAYS outside the collapsible block
    if (result.sectionSummaries?.suggestions) {
      body += `${result.sectionSummaries.suggestions}\n`;
    }
    body += '\n';

    // Build collapsible content (just the items, no description inside)
    let suggestionsContent = '';
    suggestions.forEach(f => {
      suggestionsContent += `- **${f.title}**`;
      if (f.file) {
        suggestionsContent += ` — \`${f.file}${f.line ? ':' + f.line : ''}\``;
      }
      suggestionsContent += '\n';

      if (f.description) {
        suggestionsContent += `  ${f.description}\n`;
      }

      if (f.suggestedFix) {
        suggestionsContent += '\n  **Suggested fix:**\n';
        suggestionsContent += '  ```suggestion\n';
        suggestionsContent += `  ${f.suggestedFix.split('\n').join('\n  ')}\n`;
        suggestionsContent += '  ```\n';
      }
      suggestionsContent += '\n';
    });

    body += '<details>\n<summary>View suggestions</summary>\n\n';
    body += suggestionsContent;
    body += '</details>\n\n';
  }

  // Footer with version and timestamp
  const timestamp = formatTimestamp(new Date(), timezone);
  const metadata = formatMetadata(version);
  body += `---\n\n*Generated by Open Review* · **v${version}** · ${timestamp}\n\n${metadata}`;

  return body;
}

module.exports = { formatForGitHub, formatTimestamp, formatMetadata, REVIEW_MARKER };