const REVIEW_MARKER = '*Generated by Open Review*';
const METADATA_START = '<!-- open-review:meta';
const METADATA_END = '-->';

const TIMEZONE = process.env.TIMEZONE || 'UTC';

const ICON_STOP = 'https://raw.githubusercontent.com/primer/octicons/main/icons/stop-16.svg';
const ICON_DIFF_REMOVED = 'https://raw.githubusercontent.com/primer/octicons/main/icons/diff-removed-16.svg';
const ICON_COMMENT_DISCUSSION = 'https://raw.githubusercontent.com/primer/octicons/main/icons/comment-discussion-16.svg';
const ICON_LIGHT_BULB = 'https://raw.githubusercontent.com/primer/octicons/main/icons/light-bulb-16.svg';

function formatTimestamp(date = new Date()) {
  try {
    return date.toLocaleString('en-US', {
      timeZone: TIMEZONE,
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    });
  } catch (error) {
    console.warn(`Invalid timezone '${TIMEZONE}', falling back to UTC`);
    return date.toLocaleString('en-US', {
      timeZone: 'UTC',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    });
  }
}

function formatMetadata(version) {
  return `${METADATA_START}\nversion: ${version}\ngenerated: ${new Date().toISOString()}\n${METADATA_END}`;
}

function formatFileLink(file, line, baseUrl) {
  const display = line ? `${file}:${line}` : file;
  if (!baseUrl) return `\`${display}\``;
  const url = `${baseUrl}${file}${line ? '#L' + line : ''}`;
  return `[\`${display}\`](${url})`;
}

function detectCodeLanguage(file, fix) {
  if (!fix) return '';
  const lines = fix.split('\n');
  const hasDiffMarkers = lines.some(l => l.startsWith('+ ') || l.startsWith('- ') || l.startsWith('@@'));
  if (hasDiffMarkers) return 'diff';

  const ext = file?.split('.').pop()?.toLowerCase() || '';
  const map = {
    php: 'php',
    js: 'javascript',
    jsx: 'jsx',
    ts: 'typescript',
    tsx: 'tsx',
    py: 'python',
    rb: 'ruby',
    go: 'go',
    rs: 'rust',
    java: 'java',
    kt: 'kotlin',
    swift: 'swift',
    c: 'c',
    cpp: 'cpp',
    h: 'c',
    cs: 'csharp',
    json: 'json',
    yml: 'yaml',
    yaml: 'yaml',
    xml: 'xml',
    html: 'html',
    css: 'css',
    scss: 'scss',
    sql: 'sql',
    sh: 'bash',
    bash: 'bash',
    zsh: 'bash',
    md: 'markdown',
    dockerfile: 'dockerfile',
  };
  return map[ext] || '';
}

function formatSummaryTable(counts) {
  const sections = [
    { key: 'mustFix', label: 'Must%20fix', color: 'd73a49', count: counts.mustFix },
    { key: 'shouldFix', label: 'Should%20fix', color: 'd4a017', count: counts.shouldFix },
    { key: 'questions', label: 'Questions', color: '0969da', count: counts.questions },
    { key: 'suggestions', label: 'Suggestions', color: '57606a', count: counts.suggestions },
  ].filter(s => s.count > 0);

  if (sections.length === 0) return '';

  const headers = sections.map(s =>
    `<th align="center"><img src="https://img.shields.io/badge/${s.label}-${s.color}?style=flat-square" alt="${s.key}"></th>`
  ).join('');

  const values = sections.map(s =>
    `<td align="center"><strong>${s.count}</strong></td>`
  ).join('');

  return `<table width="100%">\n  <thead>\n    <tr>${headers}</tr>\n  </thead>\n  <tbody>\n    <tr>${values}</tr>\n  </tbody>\n</table>\n`;
}

function formatSection({ icon, title, count, countColor, summary, content, isCollapsible = false }) {
  const countBadge = `https://img.shields.io/badge/-${count}-${countColor}?style=flat-square`;
  let section = `\n## <img src="${icon}" height="16" alt=""> ${title} <img align="right" src="${countBadge}" height="20">\n\n`;

  if (summary) {
    section += `${summary}\n\n`;
  }

  if (isCollapsible) {
    section += '<details>\n<summary>View ' + title.toLowerCase() + '</summary>\n\n';
  }

  section += content;

  if (isCollapsible) {
    section += '\n</details>\n';
  }

  return section;
}

function formatForGitHub(result, version = 1, baseUrl = '') {
  const verdicts = {
    approve:         { badge: 'https://forthebadge.com/api/badges/generate?panels=2&primaryLabel=LGTM&secondaryLabel=approve%20and%20merge&primaryBGColor=%232ea44f&secondaryBGColor=%23ffffff&primaryTextColor=%23ffffff&secondaryTextColor=%232ea44f&primaryFontSize=14&primaryFontWeight=700&primaryLetterSpacing=1&primaryTextTransform=uppercase&secondaryFontSize=14&secondaryFontWeight=400&secondaryLetterSpacing=0&secondaryTextTransform=none' },
    request_changes: { badge: 'https://forthebadge.com/api/badges/generate?panels=2&primaryLabel=CHANGES%20REQUESTED&secondaryLabel=do%20not%20merge&primaryBGColor=%23d73a49&secondaryBGColor=%23ffffff&primaryTextColor=%23ffffff&secondaryTextColor=%23d73a49&primaryFontSize=14&primaryFontWeight=700&primaryLetterSpacing=1&primaryTextTransform=uppercase&secondaryFontSize=14&secondaryFontWeight=400&secondaryLetterSpacing=0&secondaryTextTransform=none' },
    comment:         { badge: 'https://forthebadge.com/api/badges/generate?panels=2&primaryLabel=HOLD&secondaryLabel=let%27s%20discuss%20the%20approach&primaryBGColor=%23d4a017&secondaryBGColor=%23ffffff&primaryTextColor=%23ffffff&secondaryTextColor=%23d4a017&primaryFontSize=14&primaryFontWeight=700&primaryLetterSpacing=1&primaryTextTransform=uppercase&secondaryFontSize=14&secondaryFontWeight=400&secondaryLetterSpacing=0&secondaryTextTransform=none' }
  };

  const v = verdicts[result.verdict] || verdicts.comment;
  let body = `<img src="${v.badge}" height="32" alt="">\n\n`;

  if (result.verdict !== 'approve' && result.summary) {
    body += `${result.summary}\n\n`;
  }

  const findings = result.findings || [];
  const critical    = findings.filter(f => f.severity === 'critical');
  const warnings    = findings.filter(f => f.severity === 'warning');
  const questions   = findings.filter(f => f.type === 'question');
  const suggestions = findings.filter(f => f.type === 'suggestion' || (f.severity === 'info' && f.type !== 'question'));

  const counts = {
    mustFix: critical.length,
    shouldFix: warnings.length,
    questions: questions.length,
    suggestions: suggestions.length,
  };

  const table = formatSummaryTable(counts);
  if (table) {
    body += table;
  }

  if (critical.length > 0) {
    let content = '';
    critical.forEach((f, i) => {
      content += `${i + 1}. **${f.title}**`;
      if (f.file) content += ` — ${formatFileLink(f.file, f.line, baseUrl)}`;
      content += '\n';
      if (f.description) content += `   ${f.description}\n`;
      if (f.suggestedFix) {
        content += '\n   **Suggested fix:**\n';
        const lang = detectCodeLanguage(f.file, f.suggestedFix);
        content += `   \`\`\`${lang}\n`;
        content += `   ${f.suggestedFix.split('\n').join('\n   ')}\n`;
        content += '   ```\n';
      }
      content += '\n';
    });
    body += formatSection({
      icon: ICON_STOP,
      title: 'Must fix',
      count: critical.length,
      countColor: 'd73a49',
      summary: result.sectionSummaries?.mustFix,
      content
    });
  }

  if (warnings.length > 0) {
    let content = '';
    warnings.forEach(f => {
      content += `- **${f.title}**`;
      if (f.file) content += ` — ${formatFileLink(f.file, f.line, baseUrl)}`;
      content += '\n';
      if (f.description) content += `  ${f.description}\n`;
      if (f.suggestedFix) {
        content += '\n  **Suggested fix:**\n';
        const lang = detectCodeLanguage(f.file, f.suggestedFix);
        content += `  \`\`\`${lang}\n`;
        content += `  ${f.suggestedFix.split('\n').join('\n  ')}\n`;
        content += '  ```\n';
      }
      content += '\n';
    });
    body += formatSection({
      icon: ICON_DIFF_REMOVED,
      title: 'Should fix',
      count: warnings.length,
      countColor: 'd4a017',
      summary: result.sectionSummaries?.shouldFix,
      content
    });
  }

  if (questions.length > 0) {
    let content = '';
    questions.forEach(f => {
      content += `- **${f.title}**\n`;
      if (f.description) content += `  ${f.description}\n`;
      content += '\n';
    });
    body += formatSection({
      icon: ICON_COMMENT_DISCUSSION,
      title: 'Questions',
      count: questions.length,
      countColor: '0969da',
      summary: result.sectionSummaries?.questions,
      content
    });
  }

  if (suggestions.length > 0) {
    let content = '';
    suggestions.forEach(f => {
      content += `- **${f.title}**`;
      if (f.file) content += ` — ${formatFileLink(f.file, f.line, baseUrl)}`;
      content += '\n';
      if (f.description) content += `  ${f.description}\n`;
      if (f.suggestedFix) {
        content += '\n  **Suggested fix:**\n';
        const lang = detectCodeLanguage(f.file, f.suggestedFix);
        content += `  \`\`\`${lang}\n`;
        content += `  ${f.suggestedFix.split('\n').join('\n  ')}\n`;
        content += '  ```\n';
      }
      content += '\n';
    });
    body += formatSection({
      icon: ICON_LIGHT_BULB,
      title: 'Suggestions',
      count: suggestions.length,
      countColor: '57606a',
      summary: result.sectionSummaries?.suggestions,
      content,
      isCollapsible: true
    });
  }

  const timestamp = formatTimestamp();
  const metadata = formatMetadata(version);
  body = body.trimEnd();
  body += `\n\n---\n\n*Generated by Open Review* · **v${version}** · ${timestamp}\n\n${metadata}`;

  return body;
}

module.exports = { formatForGitHub, formatTimestamp, formatMetadata, REVIEW_MARKER };
